spring.application.name=assistant

# Chat API ??
spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode
spring.ai.openai.api-key=${OPENAI_API_KEY:your-dashscope-api-key}
spring.ai.openai.chat.options.model=qwen-plus
spring.ai.openai.chat.enabled=true

# Embedding API ??
spring.ai.openai.embedding.options.model=text-embedding-v3
#spring.ai.model.embedding=openai
spring.ai.vectorstore.pgvector.dimensions=1024

#spring.ai.openai.api-key=${OPENAI_API_KEY:your-api-key-here}
#spring.ai.openai.chat.options.model=gpt-4o-mini
#spring.ai.openai.chat.enabled=true
#spring.ai.model.embedding=openai
#spring.ai.vectorstore.pgvector.dimensions=1536

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.datasource.password=postgres
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
